 export const FavoritesPhotos = [
    {
      "id":1,
      "type":"image",
      "ancestor":[
         1
      ],
      "Name":"1.jpg",
      "Owner":1,
      "DateCreated":"01-Jan-2020",
      "tags":[
         {
            "facetag":[
               {
                  "uid":1
               },
               {
                  "uid":2
               }
            ],
            "keywordtag":[
               {
                  "kid":1
               },
               {
                  "kid":2
               }
            ]
         }
      ]
   },
   {
      "id":2,
      "type":"image",
      "ancestor":[
         1
      ],
      "Name":"OIP.jpg",
      "Owner":1,
      "DateCreated":"01-Jan-2022",
      "tags":[
         {
            "facetag":[
               {
                  "uid":1
               },
               {
                  "uid":2
               }
            ],
            "keywordtag":[
               {
                  "kid":1
               },
               {
                  "kid":2
               }
            ]
         }
      ]
   },
   {
      "id":3,
      "type":"image",
      "ancestor":[
         1
      ],
      "Name":"1602511365246.jpg",
      "Owner":1,
      "DateCreated":"01-Jan-2021",
      "tags":[
         {
            "facetag":[
               {
                  "uid":1
               },
               {
                  "uid":2
               }
            ],
            "keywordtag":[
               {
                  "kid":1
               },
               {
                  "kid":2
               }
            ]
         }
      ]
   },
   {
      "id":4,
      "type":"image",
      "ancestor":[
         1
      ],
      "Name":"digital-minimalism-benefits-696x464.jpg",
      "Owner":1,
      "DateCreated":"01-Jan-2024",
      "tags":[
         {
            "facetag":[
               {
                  "uid":1
               },
               {
                  "uid":2
               }
            ],
            "keywordtag":[
               {
                  "kid":1
               },
               {
                  "kid":2
               }
            ]
         }
      ]
   },
   {
      "id":5,
      "type":"image",
      "ancestor":[
         1
      ],
      "Name":"OIP (1).jpg",
      "Owner":1,
      "DateCreated":"01-Jan-2025",
      "tags":[
         {
            "facetag":[
               {
                  "uid":2
               }
            ],
            "keywordtag":[
               {
                  "kid":1
               },
               {
                  "kid":2
               }
            ]
         }
      ]
   },
   {
      "id":6,
      "type":"image",
      "ancestor":[
         1
      ],
      "Name":"OIP (2).jpg",
      "Owner":1,
      "DateCreated":"01-Jan-2023",
      "tags":[
         {
            "facetag":[
               {
                  "uid":2
               }
            ],
            "keywordtag":[
               {
                  "kid":1
               },
               {
                  "kid":2
               }
            ]
         }
      ]
   },
   {
      "id":7,
      "type":"image",
      "ancestor":[
         1
      ],
      "Name":"OIP (4).jpg",
      "Owner":1,
      "DateCreated":"01-Jan-2021",
      "tags":[
         {
            "facetag":[
               
            ],
            "keywordtag":[
               
            ]
         }
      ]
   },
   {
      "id":8,
      "type":"image",
      "ancestor":[
         1
      ],
      "Name":"OIP (5).jpg",
      "Owner":1,
      "DateCreated":"01-Jan-2026",
      "tags":[
         {
            "facetag":[
               
            ],
            "keywordtag":[
               
            ]
         }
      ]
   },
   {
      "id":9,
      "type":"image",
      "ancestor":[
         1,
         9
      ],
      "Name":"digital-minimalism-benefits-696x464.jpg",
      "Owner":1,
      "DateCreated":"01-Jan-2024",
      "tags":[
         {
            "facetag":[
               
            ],
            "keywordtag":[
               
            ]
         }
      ]
   },
   {
      "id":10,
      "type":"image",
      "ancestor":[
         1,
         9
      ],
      "Name":"OIP (1).jpg",
      "Owner":1,
      "DateCreated":"01-Jan-2021",
      "tags":[
         {
            "facetag":[
               
            ],
            "keywordtag":[
               
            ]
         }
      ]
   },
   {
      "id":11,
      "type":"image",
      "ancestor":[
         1,
         9
      ],
      "Name":"OIP (2).jpg",
      "Owner":1,
      "DateCreated":"01-Jan-2022",
      "tags":[
         {
            "uid":2
         }
      ],
      "tags":[
         {
            "facetag":[
               
            ],
            "keywordtag":[
               
            ]
         }
      ]
   },
   {
      "id":12,
      "type":"image",
      "ancestor":[
         1,
         9
      ],
      "Name":"OIP (4).jpg",
      "Owner":1,
      "DateCreated":"01-Jan-2023",
      "tags":[
         {
            "facetag":[
               
            ],
            "keywordtag":[
               
            ]
         }
      ]
   }
]